# Generated by Django 5.0.1 on 2024-01-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_model_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Book',
        ),
    ]
